version: '3'
services:
  notebook:
    build: .
    volumes:
      - ./notebooks:/notebooks
      - ./jupyter:/root/.jupyter
    ports:
      - "8005:8888"
    networks:
      - backend

networks:
  backend:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.61.0/24